$modelname player/spy.mdl

// Define the variable that spy.qci will use to load the dmx files for high and low end models.
$definevariable dmxFile "../parts/dmx/spy_morphs_low.dmx"

$definevariable 01_lod "../parts/dmx/spy_lod_01_low.dmx"
$definevariable 02_lod "../parts/dmx/spy_lod_02_low.dmx"
$definevariable 03_lod "../parts/dmx/spy_lod_03_low.dmx"
$definevariable 04_lod "../parts/dmx/spy_lod_04_low.dmx"
$definevariable 05_lod "../parts/dmx/spy_lod_05_low.dmx"


$include spy.qci

